:imagesdir: ../../assets/images

== 개념 소개

include::../style.adoc[]

{product_name_rhdh} 및 일반적인 내부 개발자 플랫폼은 조직 내 소프트웨어와 관련된 데이터를 수집하고 표시하는 모듈형 시스템으로 볼 수 있습니다.

{product_name_rhdh}의 핵심 기능은 다음과 같습니다.

* 소프트웨어 카탈로그(Software Catalog)
* 소프트웨어 템플릿(Software Templates)
* 기술 문서(TechDocs)
* Kubernetes 통합

=== 소프트웨어 템플릿

소프트웨어 템플릿은 과거에 "Golden Paths"라고도 불렸습니다. 
이러한 템플릿은 플랫폼 엔지니어가 설계하고 큐레이션하여 조직의 모범 사례를 따르는 새로운 소프트웨어 구성 요소에 대한 시작점을 제공합니다. 또한 기존 소스 코드 저장소를 패치하고 업데이트하는 데도 사용할 수 있습니다.

소프트웨어 템플릿에 대한 자세한 내용은 이후 모듈에서 더 깊이 다룰 예정입니다!

=== 소프트웨어 카탈로그

소프트웨어 카탈로그는 조직 내 모든 소프트웨어를 중앙에서 관리하는 자산 추적 시스템입니다. 여기에는 다음과 같은 **엔터티(Entities)**가 저장 및 추적됩니다.

* 컴포넌트(Components): 개별 소프트웨어 단위 (마이크로서비스, 웹사이트, 라이브러리 등)
* 리소스(Resources): 데이터베이스, S3 버킷, 브로커 등 인프라 관련 자원
* API: REST, gRPC, GraphQL API 등의 인터페이스
* 시스템(Systems): 애플리케이션이나 플랫폼을 구성하는 여러 컴포넌트의 모음
* 도메인(Domains): 시스템과 엔터티를 더 큰 범주로 그룹화한 개념
* 사용자(User): 조직의 개별 사용자
* 그룹(Group): 사용자의 그룹

엔터티는 일반적으로 다음 세 가지 중 한 방식으로 가져와 동기화됩니다.

. 자동으로 검색하고 가져오는 플러그인 사용
. UI에서 엔티티를 포함하는 저장소에 대한 링크를 제공하여 수동으로 등록
. Backstage 구성 파일에 선언

어떤 방법을 사용하든, 엔터티 정보는 정기적으로 동기화되어 소프트웨어 카탈로그가 최신 상태로 유지됩니다. 이번 워크샵에서는 위의 세 가지 방법을 모두 활용하게 됩니다.

Git 저장소에 엔터티 정보를 저장하는 경우, 일반적으로 _catalog-info.yaml_ 파일에 해당 정보를 기록합니다. 이 파일은 다음과 같은 형식을 가집니다.

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-amazing-microservice
  description: A microservice written to do amazing things

  # Annotations are typically used to provide extra context to plugins, e.g TechDocs
  annotations:
    # Tells the TechDocs plugin where to find documentation sources. In this case
    # "dir:." means in the root of the repo containing this catalog-info.yaml
    backstage.io/techdocs-ref: dir:.

  # Arbitrary list of string that can be used to filter Entities in the Software Catalog
  tags:
    - docs

spec:
  type: Documentation
  lifecycle: development

  # Reference to the User or Group Entity that is responsible this Component
  owner: "pe1"
```

사용자와 그룹은 다른 엔터티(컴포넌트, 리소스, API 등)의 소유자로 지정할 수 있습니다. 이 개념이 추상적으로 느껴지더라도 걱정하지 마세요. 곧 명확한 예시를 통해 이해할 수 있습니다. 
잘 정리된 소프트웨어 카탈로그를 사용하면 개발자가 API 문서와 해당 API를 지원하는 컴포넌트를 담당하는 팀을 쉽게 찾을 수 있게 해줍니다.

=== 플러그인

Backstage와 그 확장인 {product_name_rhdh}는 플러그인 개념을 지원합니다. 플러그인을 활용하는 것은 IDP에서 원하는 기능을 구현하는 데 중요한 부분입니다.

현재, 업스트림 Backstage에서 인스턴스를 실행하고 플러그인을 추가하려면 플랫폼 엔지니어가 다음과 같은 단계를 수행해야 합니다.

. Node.js와 npm을 사용하여 Backstage 프로젝트 생성
. npm에서 플러그인 설치
. Backstage React 및 Node.js 소스 코드를 편집하여 플러그인 로드
. 컨테이너 이미지를 빌드하고 배포

하지만 {product_name_rhdh}는 동적으로 플러그인을 로드할 수 있는 기능을 제공합니다. 
이는 현재 업스트림 Backstage에서는 지원되지 않는 기능으로, 자세한 내용은 https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html/introduction_to_plugins/index#con-rhdh-plugins[{product_name_rhdh} documentation^, window="content"]에서 확인할 수 있습니다. 
{product_name_rhdh}에서 동적 플러그인 지원은 코드 편집 및 {product_name_rhdh} 컨테이너 이미지 재빌드를 하지 않고도 새로운 플러그인을 설치할 수 있게 해줍니다.

동적 플러그인의 실제 동작도 곧 실습을 통해 확인할 수 있습니다.

=== {product_name_rhdh} 구성 이해

업스트림 Backstage는 https://backstage.io/docs/conf/[app-config.yaml^, window="content"] 파일을 사용하여 구성 값을 정의합니다. {product_name_rhdh}도 마찬가지입니다.

간단한 Backstage 구성 파일은 다음과 같은 형태를 띕니다.

```yaml
# Define authentication configuration (this example is for testing only!)
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

# Static configuration for the Software Catalog. Can be used to import
# entities on startup, and restrict the entity types that can be imported.
catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: https://github.com/org-name/repo-name/entities.yaml

# A configuration for the TechDocs plugin. This example instructs the plugin to
# build documentation at runtime, instead of pulling prebuilt HTML from S3
techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local
```

이 워크샵 환경은 {product_name_rhdh} Helm Chart를 사용하여 내부 개발자 플랫폼폼을 설치하고 관리하고 있기 때문에, 구성 값은 Helm Values 파일의 upstream.backstage.appConfig 속성 아래에 중첩되어 있습니다. 
구성 파일을 보려면 https://gitlab-gitlab.{openshift_cluster_ingress_domain}/rhdh/developer-hub-config/-/blob/main/values.yaml[GitLab에서 rhdh/developer-hub-config repository^, window="gitlab"]에 방문하세요.

워크샵 환경은 GitLab에 있는 이 리포지토리가 https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}/applications[OpenShift GitOps의 `backstage` Application^, window="argo"]을 사용하여 지속적으로 모니터링되고 배포되도록 미리 구성되었습니다. 
(OpenShift GitOps에 로그인할 때 admin 사용자와 비밀번호 {openshift_gitops_password}를 사용하세요)

Gitlab에서 Helm Values 파일의 내용을 변경하면, 변경한 구성을 반영하여 {product_name_rhdh} 컨테이너가 재배포 됩니다.

이제 준비가 끝났으니, {product_name_rhdh} 인스턴스 구성을 시작해 보겠습니다!
