:imagesdir: ../assets/images

= 모듈 2: 내부 개발자 플랫폼 설계

include::../style.adoc[]

== 개요

{product_name_rhdh}는 내부 개발자 플랫폼을 구축하기 위한 https://backstage.io/[Backstage^, window="content"] 프레임워크를 기반으로 합니다. 이 프로젝트는 2020년 Spotify에 의해 https://www.cncf.io/projects/backstage/[CNCF^, window="content"]에 기부되었습니다. 
플랫폼 엔지니어는 {product_name_rhdh}를 활용하여 내부 개발자 플랫폼을 구축할 수 있으며, 이를 위해 다양한 데이터 소스와의 통합, 기존 소프트웨어 구성 요소 및 인프라·리소스 카탈로그화, SSO(싱글 사인온) 구성 등을 수행하게 됩니다.

이 모듈에서는 {product_name_rhdh} 인스턴스를 설계, 설치 및 부트스트랩하여 조직 내 특정 개발자 그룹을 위한 최소 실행 가능 내부 개발자 플랫폼을 구축하는 방법을 학습합니다.

초기 개발자 플랫폼의 주요 활용 사례는 다음과 같습니다.

* 소프트웨어 구성 요소 및 종속성을 셀프 서비스 방식으로 탐색
* CI/CD 파이프라인 가시성 확보
* 문서 호스팅
* 조직의 모범 사례를 준수하는 프로젝트 스캐폴딩

== 모듈 목표

이전에 정의한 활용 사례를 충족하려면 {product_name_rhdh}를 기존 플랫폼, 도구 및 인프라와 통합하도록 구성해야 합니다. 
예를 들어, 조직에서 지속적 통합을 위해 OpenShift Pipelines를 사용한다면, {product_name_rhdh} 인스턴스에서 적절한 통합을 설정하여 https://tekton.dev/docs/pipelines/pipelineruns/[Pipeline Runs^, window="content"]을 수행하는 OpenShift 클러스터에서 데이터를 가져오고 표시할 수 있도록 해야 합니다.

내부 개발자 플랫폼의 가치는 이를 구축하는 플랫폼 엔지니어와 사용하는 개발자가 투자하는 노력과 고민에 비례한다고 볼 수 있습니다.

이 모듈에서는 다음을 학습합니다.

* SSO(Single Sign-On), SCM(Source Code Management), RBAC, 리소스, 기존 자산산 등 플랫폼 요구사항과 종속성 식별
* GitLab 및 Keycloak과 같은 종속 서비스와 {product_name_rhdh} 통합
* https://backstage.io/docs/features/software-catalog/[Backstage Entities^, window="content"] 개념 학습 (예: 컴포넌트, API, 문서)
* 개발자 온보딩을 위한 플랫폼 준비


== 워크샵 환경

워크숍 환경은 다음 소프트웨어 및 플랫폼 구성 요소로 사전 구성되어 있습니다.

* Red Hat Build of Keycloak
* OpenShift GitOps
* OpenShift Pipelines
* GitLab

이 워크샵에서는 조직이 이러한 도구를 표준으로 사용한다고 가정하며, 플랫폼 엔지니어로서의 목표는 이를 {product_name_rhdh}와 통합하는 것입니다.
